name: Django CI

on:
  push:
    branches: ["master"]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ github.event.repository.name }}/
            git fetch --all
            git checkout main --force
            git reset --hard
            git pull
            echo "${{ secrets.ENV }}" > .env
            sh deploy.sh